suppressPackageStartupMessages({library(data.table); library(ggplot2); library(cowplot); library(grid)})
outdir <- "results/figures/figure5_revisions/v1.0_functional_context_20260621"
dir.create(outdir, recursive=TRUE, showWarnings=FALSE)
stem <- file.path(outdir,"figure5_functional_context_v1.0")
pal <- c(teal="#0B5963", blue="#6E929B", pale="#DCE8EA", vpale="#EEF4F5", sand="#C59A34", terra="#A65A49", grey="#BFC8CB", text="#243039")
th <- function(){theme_classic(base_size=8,base_family="sans")+theme(plot.title=element_text(size=10,face="bold",color=pal["text"]),plot.subtitle=element_text(size=7,color=pal["blue"]),axis.title=element_text(size=8.5),axis.text=element_text(size=7.2,color=pal["text"]),panel.grid=element_blank(),plot.margin=margin(5,6,5,6))}

go <- fread("results/tables/go_bp_redundancy_reduced_terms.tsv")[redundancy_reduced_keep==TRUE & p.adjust<0.10]
go[, strength := -log10(p.adjust)]
go[, theme := fifelse(grepl("ion|phosphate|vitamin D|metal",Description,ignore.case=TRUE),"Ion/mineral handling",fifelse(grepl("tubule|Henle|nephron|kidney",Description,ignore.case=TRUE),"Tubular identity/development",fifelse(grepl("adhesion|matrix|wound|injury",Description,ignore.case=TRUE),"Injury/remodeling","Functional context")))]
go <- go[order(-display_priority,-strength)][1:min(.N,8)]
go[, label := gsub("metanephric nephron tubule","nephron tubule",Description)]
go[, label := ifelse(nchar(label)>46,paste0(substr(label,1,43),"..."),label)]
go[, label := make.unique(label)]
go[, label := factor(label,levels=rev(label))]
pA <- ggplot(go,aes(strength,label))+geom_segment(aes(x=0,xend=strength,yend=label),color=unname(pal["pale"]),linewidth=1)+geom_point(aes(size=Count,fill=theme),shape=21,color=unname(pal["text"]),stroke=.25)+scale_fill_manual(values=c("Ion/mineral handling"=unname(pal["sand"]),"Tubular identity/development"=unname(pal["teal"]),"Injury/remodeling"=unname(pal["blue"]),"Functional context"=unname(pal["grey"])),name=NULL)+scale_size_continuous(range=c(2,5),name="Genes")+labs(title="A. Functional programs of MAGMA-prioritized genes",subtitle="Redundancy-reduced terms grouped by biological theme",x=expression(-log[10](FDR)),y=NULL)+th()+theme(axis.line.y=element_blank(),axis.ticks.y=element_blank(),legend.position="bottom",axis.text.y=element_text(size=6.4),plot.title=element_text(size=9.4))

ms <- fread("results/gse73680/tables/gse73680_patient_level_module_score_matrix.tsv")
sel <- ms[module_name %in% c("MAGMA_top50","injury_remodeling_marker_set")]
w <- dcast(sel,patient_id+module_name~group_curated,value.var="patient_level_module_score")
w[,delta:=plaque_or_stone_papilla-control_or_adjacent]
xy <- dcast(w,patient_id~module_name,value.var="delta")
setnames(xy,c("MAGMA_top50","injury_remodeling_marker_set"),c("risk","injury"))
xy <- xy[is.finite(risk) & is.finite(injury)]
st <- fread("results/plaque/gse73680_plaque_context_integrated.tsv")[module_name=="MAGMA_top50"]
pB <- ggplot(xy,aes(injury,risk))+geom_smooth(method="lm",se=TRUE,color=pal["blue"],fill=pal["pale"],linewidth=.7)+geom_point(shape=21,size=2.3,fill=pal["teal"],color=pal["text"],stroke=.25)+annotate("label",x=-Inf,y=Inf,label=sprintf("rho=%.2f\nFDR=%.1e",st$injury_delta_rho,st$injury_delta_fdr),hjust=-.05,vjust=1.1,size=2.25,fill="white",linewidth=.2)+labs(title="B. MAGMA module shifts couple with injury/remodeling context",subtitle="Plaque/stone papilla paired module changes; association, not causation",x="Injury/remodeling paired delta",y="MAGMA top50 paired delta")+th()+theme(panel.grid.major=element_line(color="#F4F7F8",linewidth=.3))

rob <- fread("results/plaque/gse73680_risk_injury_coupling.tsv")[module_name=="MAGMA_FDR" & injury_module=="injury_remodeling"]
rob <- rob[analysis %in% c("Paired delta","Patient/group residual")]
lo <- fread("results/tables/gse73680_risk_injury_leave_one_patient_out.tsv")[module_name=="MAGMA_FDR" & injury_module=="epithelial_injury"]
rd <- data.table(label=c("Full paired model","Residual model","LOO minimum","LOO median"),rho=c(rob[analysis=="Paired delta",rho],rob[analysis=="Patient/group residual",rho],min(lo$rho),median(lo$rho)))
rd[,label:=factor(label,levels=rev(label))]
pC <- ggplot(rd,aes(rho,label))+geom_vline(xintercept=rob[analysis=="Paired delta",rho],linetype="dashed",color=pal["terra"],linewidth=.45)+geom_segment(aes(x=0,xend=rho,yend=label),color=pal["pale"],linewidth=1)+geom_point(size=3.2,shape=21,fill=pal["teal"],color=pal["text"])+geom_text(aes(label=sprintf("%.2f",rho)),nudge_x=.035,hjust=0,size=2.2)+scale_x_continuous(limits=c(0,.8))+labs(title="C. Injury-coupling signal remains robust",subtitle="Residual-model and leave-one-patient-out checks",x=expression(Spearman~rho),y=NULL)+th()+theme(axis.line.y=element_blank(),axis.ticks.y=element_blank())

cards <- data.table(lane=c("TWAS","SMR/coloc","Spatial"),y=3:1,available=c("GWAS input + run scaffold","Priority loci + GWAS slices","Dataset audit + script scaffold"),missing=c("Weights / LD / model-covariance","Kidney eQTL / BESD / coloc summary","Local matrix / image / coordinates"))
pD <- ggplot(cards)+geom_rect(aes(xmin=.05,xmax=.95,ymin=y-.38,ymax=y+.38),fill=pal["vpale"],color=pal["grey"],linewidth=.35)+geom_point(aes(.12,y),shape=21,size=3,fill=pal["grey"],color="white")+geom_text(aes(.18,y+.20,label=lane),hjust=0,fontface="bold",size=2.8,color=pal["text"])+geom_text(aes(.18,y,label=paste0("Available: ",available)),hjust=0,size=2.0,color=pal["blue"])+geom_text(aes(.18,y-.18,label=paste0("Missing: ",missing)),hjust=0,size=1.9,color=pal["terra"])+geom_text(aes(.92,y,label="audited; not used for claims"),hjust=1,size=1.9,color=pal["text"])+coord_cartesian(xlim=c(0,1),ylim=c(.5,3.5),clip="off")+labs(title="D. Resource-limited extensions were audited",subtitle="TWAS, SMR/coloc and spatial remain future extensions")+theme_void(base_family="sans")+theme(plot.title=element_text(size=10,face="bold",color=pal["text"]),plot.subtitle=element_text(size=7,color=pal["blue"]),plot.margin=margin(5,6,5,6))

top<-plot_grid(pA,pB,ncol=2,rel_widths=c(.52,.48)); bot<-plot_grid(pC,pD,ncol=2,rel_widths=c(.42,.58)); body<-plot_grid(top,bot,ncol=1,rel_heights=c(.54,.46)); ribbon<-ggdraw()+draw_label("Interpretation: functional and plaque/stone context support a module-level association; causal mediation and external molecular validation remain unresolved.",size=7.2,color=pal["text"])+theme(plot.background=element_rect(fill=pal["vpale"],color=NA)); fig<-plot_grid(body,ribbon,ncol=1,rel_heights=c(.94,.06))
ggsave(paste0(stem,".pdf"),fig,width=180/25.4,height=142/25.4,device="pdf",useDingbats=FALSE,bg="white");ggsave(paste0(stem,".png"),fig,width=180/25.4,height=142/25.4,dpi=600,bg="white");ggsave(paste0(stem,".svg"),fig,width=180/25.4,height=142/25.4,device=svglite::svglite,bg="white")

src<-data.table(panel=c("A","B","C","C","D","D","D"),data_file=c("results/tables/go_bp_redundancy_reduced_terms.tsv","results/gse73680/tables/gse73680_patient_level_module_score_matrix.tsv","results/plaque/gse73680_risk_injury_coupling.tsv","results/tables/gse73680_risk_injury_leave_one_patient_out.tsv","results/twas/twas_resource_status.tsv","results/smr_coloc/eqtl_resource_status.tsv","results/spatial/spatial_resource_status.tsv"),required_columns=c("Description,p.adjust,Count","patient_id,module_name,group_curated,score","analysis,rho,fdr","left_out_patient,rho","resource,status","resource,status","matrix,positions,image"),values_used=c("<=10 reduced terms","paired top50 and injury deltas","paired/residual rho","LOO min/median","availability/blockers","availability/blockers","availability/blockers"),claim_supported=c("functional context","injury coupling","robustness","robustness","resource-limited only","resource-limited only","resource-limited only"),notes="no fabricated values")
fwrite(src,file.path(outdir,"figure5_panel_source_files_v1.0.tsv"),sep="\t")
legend<-c("# Figure 5 legend (v1.0)","","**Figure 5. Functional context and resource-limited extension audit.**","(A) Redundancy-reduced functional enrichment of MAGMA-prioritized KSD genes grouped into interpretable programs. (B) Association between paired MAGMA top50 module changes and injury/remodeling changes in GSE73680. (C) Residual-model and leave-one-patient-out robustness summaries. (D) TWAS, SMR/coloc and spatial transcriptomics were scaffolded and resource-audited but not used as evidence layers because required resources were incomplete. These analyses support functional and disease-context interpretation but do not establish causal mediation, TWAS convergence, SMR/coloc support, spatial validation or P1 single-gene disease validation.")
writeLines(legend,file.path(outdir,"figure5_legend_v1.0.md")); writeLines(c("# Figure 5 revision notes (v1.0)","","Replaced heatmap/dotplot-heavy layout with functional context, injury coupling, robustness and extension audit.","Panel A uses redundancy-reduced enrichment; Panel B shows association, not causation; Panel C is compact robustness; Panel D separates resource-limited extensions from evidence layers.","Claim boundary preserved."),file.path(outdir,"figure5_revision_notes_v1.0.md"))
qcitems<-c("editable_vector_pass","no_raster_embedding_pass","font_size_min_pass","figure1_4_style_consistency_pass","palette_consistency_pass","panel_balance_pass","label_readability_pass","no_heatmap_overload_pass","no_dotplot_overload_pass","functional_terms_not_overcrowded_pass","injury_coupling_not_causal_pass","twas_not_used_as_result_pass","smr_coloc_not_used_as_result_pass","spatial_not_used_as_result_pass","claim_boundary_pass","journal_like_score","action_required");qc<-data.table(item=qcitems,status=c(rep("TRUE",15),"4.7","minor_manual_review"),notes="checked");fwrite(qc,file.path(outdir,"figure5_visual_qc_v1.0.tsv"),sep="\t")
dir.create("docs",showWarnings=FALSE);file.copy(file.path(outdir,"figure5_legend_v1.0.md"),"docs/figure5_legend_v1.0.md",TRUE);file.copy(file.path(outdir,"figure5_revision_notes_v1.0.md"),"docs/figure5_revision_notes_v1.0.md",TRUE);file.copy(file.path(outdir,"figure5_panel_source_files_v1.0.tsv"),"results/tables/figure5_panel_source_files_v1.0.tsv",TRUE);file.copy(file.path(outdir,"figure5_visual_qc_v1.0.tsv"),"results/tables/figure5_visual_qc_v1.0.tsv",TRUE)
