suppressPackageStartupMessages({library(data.table);library(ggplot2);library(cowplot);library(grid)})
od<-"results/figures/figure5_revisions/final_functional_context_20260621";dir.create(od,recursive=TRUE,showWarnings=FALSE);stem<-file.path(od,"figure5_functional_context_final")
pal<-c(teal="#0B5963",blue="#6E929B",pale="#DCE8EA",vpale="#EEF4F5",sand="#C59A34",terra="#A65A49",grey="#BFC8CB",cool="#F4F7F8",text="#243039")
th<-function(){theme_classic(base_size=8,base_family="sans")+theme(plot.title=element_text(size=10,face="bold",color=pal["text"]),plot.subtitle=element_text(size=7,color=pal["blue"]),axis.title=element_text(size=8.5),axis.text=element_text(size=7.2,color=pal["text"]),panel.grid=element_blank(),plot.margin=margin(5,6,5,6))}
go<-fread("results/tables/go_bp_redundancy_reduced_terms.tsv")[redundancy_reduced_keep==TRUE & p.adjust<.1]
go[,theme:=fifelse(grepl("calcium|ion|phosphate|urate|vitamin|metal",Description,TRUE),"Calcium / ion handling",fifelse(grepl("Henle|tubule|nephron|kidney|renal",Description,TRUE),"TAL transport",fifelse(grepl("adhesion|junction|epithelial|matrix",Description,TRUE),"Epithelial junction","Other")))]
map<-c(Loop_TAL_influential="Loop/TAL contributors",MAGMA_top100="MAGMA top 100",MAGMA_FDR="MAGMA FDR",MAGMA_suggestive="MAGMA suggestive",P1_core="P1 core")
e<-go[gene_set%in%names(map)&theme!="Other",.(strength=max(-log10(p.adjust))),by=.(gene_set,theme)];e[,left:=unname(map[gene_set])]
cc<-fread("results/gse73680/tables/gse73680_risk_injury_paired_delta_correlations.tsv")[injury_module=="injury_remodeling"&module_name%in%c("MAGMA_top50","MAGMA_top100","MAGMA_FDR","MAGMA_suggestive","P1_core_TAL_candidates")];cm<-c(MAGMA_top50="MAGMA top 50",MAGMA_top100="MAGMA top 100",MAGMA_FDR="MAGMA FDR",MAGMA_suggestive="MAGMA suggestive",P1_core_TAL_candidates="P1 core");ce<-cc[,.(gene_set=module_name,theme="Injury / remodeling",strength=rho,left=unname(cm[module_name]))];e<-rbindlist(list(e,ce),fill=TRUE);e[,width:=strength/max(strength),by=left];e<-e[order(-width),head(.SD,3),by=left]
left_order<-c("Loop/TAL contributors","MAGMA top 50","MAGMA top 100","MAGMA FDR","MAGMA suggestive","P1 core");ln<-data.table(label=left_order,y=seq(5.4,.4,length.out=6));rn<-data.table(label=c("TAL transport","Calcium / ion handling","Epithelial junction","Injury / remodeling"),y=seq(5,.8,length.out=4));e[ln,on=.(left=label),y1:=i.y];e[rn,on=.(theme=label),y2:=i.y]
pA<-ggplot()+geom_curve(data=e,aes(x=1,y=y1,xend=4,yend=y2,linewidth=width,color=theme),curvature=.16,alpha=.62)+geom_label(data=ln,aes(1,y,label=label),hjust=0,fill=unname(pal["vpale"]),color=unname(pal["text"]),label.size=0,size=2.15)+geom_label(data=rn,aes(4,y,label=label),hjust=1,fill=unname(pal["vpale"]),color=unname(pal["text"]),label.size=0,size=2.1)+scale_color_manual(values=c("TAL transport"=unname(pal["teal"]),"Calcium / ion handling"=unname(pal["sand"]),"Epithelial junction"=unname(pal["terra"]),"Injury / remodeling"=unname(pal["blue"])),guide="none")+scale_linewidth(range=c(.35,1.8),guide="none")+coord_cartesian(xlim=c(.9,4.1),ylim=c(.1,5.7),clip="off")+labs(title="A. Functional-context evidence network",subtitle="Link width is relative within evidence layer; enrichment and coupling are not one effect scale")+theme_void(base_family="sans")+theme(plot.title=element_text(size=10,face="bold",color=pal["text"]),plot.subtitle=element_text(size=6.8,color=pal["blue"]),plot.margin=margin(5,8,5,8))

terms<-go[order(p.adjust)][!duplicated(Description)][1:8];terms[,strength:=-log10(p.adjust)];terms[,lab:=ifelse(nchar(Description)>38,paste0(substr(Description,1,35),"..."),Description)];terms[,lab:=factor(lab,levels=rev(lab))];terms[,cls:=theme]
pB<-ggplot(terms,aes(strength,lab))+geom_segment(aes(x=0,xend=strength,yend=lab),color=unname(pal["pale"]),linewidth=.9)+geom_point(aes(fill=cls,size=Count),shape=21,color=unname(pal["text"]),stroke=.25)+scale_fill_manual(values=c("TAL transport"=unname(pal["teal"]),"Calcium / ion handling"=unname(pal["sand"]),"Epithelial junction"=unname(pal["terra"]),"Injury / remodeling"=unname(pal["blue"]),"Other"=unname(pal["grey"])),name=NULL)+scale_size_continuous(range=c(2,4.5),name="Genes")+labs(title="B. Ranked non-redundant\nGO context",subtitle="Eight representative terms; shorter labels shown",x=expression(-log[10](FDR)),y=NULL)+th()+theme(plot.title=element_text(lineheight=.95),axis.line.y=element_blank(),axis.ticks.y=element_blank(),axis.text.y=element_text(size=6.6),legend.position="bottom")

cp<-fread("results/gse73680/tables/gse73680_risk_injury_paired_delta_correlations.tsv");mods<-c("MAGMA_top50","MAGMA_top100","MAGMA_FDR","MAGMA_suggestive","P1_core_TAL_candidates");cp<-cp[module_name%in%mods];ml<-c(MAGMA_top50="MAGMA top 50",MAGMA_top100="MAGMA top 100",MAGMA_FDR="MAGMA FDR",MAGMA_suggestive="MAGMA suggestive",P1_core_TAL_candidates="P1 core");il<-c(injury_remodeling="Injury/remodeling",epithelial_injury="Epithelial injury",fibrosis_ecm="Fibrosis/ECM",inflammation_immune="Inflamm./immune");cp[,module:=factor(unname(ml[module_name]),levels=rev(unname(ml[mods])))];cp[,injury:=factor(unname(il[injury_module]),levels=unname(il))];cp[,txt:=sprintf("%.2f%s",rho,ifelse(fdr<.001,"***",ifelse(fdr<.01,"**",ifelse(fdr<.05,"*",""))))];cp[,rho_band:=cut(rho,breaks=c(-Inf,.2,.4,.6,.75,Inf),labels=c("0-.2",".2-.4",".4-.6",".6-.75",">.75"))]
rho_cols<-setNames(grDevices::colorRampPalette(c(unname(pal["cool"]),unname(pal["terra"])))(5),levels(cp$rho_band));pC<-ggplot(cp,aes(injury,module,fill=rho_band))+geom_tile(color="white",linewidth=.8)+geom_text(aes(label=txt),size=2.05,color=pal["text"])+scale_fill_manual(values=rho_cols,name=expression(rho~band),drop=FALSE)+labs(title="C. Risk-injury module coupling",subtitle="Paired-delta Spearman rho\n* FDR<0.05, ** <0.01, *** <0.001",x=NULL,y=NULL)+theme_void(base_family="sans")+theme(plot.title=element_text(size=10,face="bold",color=pal["text"]),plot.subtitle=element_text(size=6.5,lineheight=.92,color=pal["blue"]),axis.text.x=element_text(size=6.3,angle=28,hjust=1),axis.text.y=element_text(size=7),legend.position="bottom",plot.margin=margin(5,8,5,8))

rob<-fread("results/plaque/gse73680_risk_injury_coupling.tsv")[module_name=="MAGMA_FDR"&injury_module=="injury_remodeling"&analysis%in%c("Paired delta","Patient/group residual")];lo<-fread("results/tables/gse73680_risk_injury_leave_one_patient_out.tsv")[module_name=="MAGMA_FDR"&injury_module=="epithelial_injury"];rd<-data.table(label=c("Paired","Residual","LOO min","LOO median"),rho=c(rob[analysis=="Paired delta",rho],rob[analysis=="Patient/group residual",rho],min(lo$rho),median(lo$rho)));rd[,label:=factor(label,levels=rev(label))]
pR<-ggplot(rd,aes(rho,label))+geom_segment(aes(x=0,xend=rho,yend=label),color=unname(pal["pale"]),linewidth=.8)+geom_point(aes(fill=grepl("LOO",label)),shape=21,size=2.8,color=unname(pal["text"]))+geom_text(aes(label=sprintf("%.2f",rho)),nudge_x=.03,hjust=0,size=1.9)+scale_fill_manual(values=c("FALSE"=unname(pal["teal"]),"TRUE"=unname(pal["blue"])),guide="none")+scale_x_continuous(limits=c(0,.8))+labs(title="D. Robustness and extension audit",subtitle="Coupling checks above; resource audit below",x=expression(Spearman~rho),y=NULL)+th()+theme(axis.text.y=element_text(size=6.3),axis.line.y=element_blank(),axis.ticks.y=element_blank(),plot.title=element_text(size=9.6),plot.subtitle=element_text(size=6.5))
cards<-data.table(lane=c("TWAS","SMR/coloc","Spatial"),y=3:1,available=c("GWAS input + scaffold","Priority loci + GWAS slices","Dataset audit + scaffold"),missing=c("weights / LD / covariance","kidney eQTL / BESD / summary","matrix / image / coordinates"));pAudit<-ggplot(cards)+geom_rect(aes(xmin=.02,xmax=.98,ymin=y-.36,ymax=y+.36),fill=pal["vpale"],color=pal["grey"],linewidth=.3)+geom_point(aes(.09,y),shape=21,size=2.6,fill=pal["grey"],color="white")+geom_text(aes(.15,y+.17,label=lane),hjust=0,fontface="bold",size=2.45,color=pal["text"])+geom_text(aes(.15,y-.02,label=paste0("Available: ",available)),hjust=0,size=1.75,color=pal["blue"])+geom_text(aes(.15,y-.20,label=paste0("Missing: ",missing)),hjust=0,size=1.7,color=pal["terra"])+geom_text(aes(.95,y,label="audited; not used for claims"),hjust=1,size=1.65,color=pal["text"])+coord_cartesian(xlim=c(0,1),ylim=c(.5,3.5))+theme_void()
pD<-plot_grid(pR,pAudit,ncol=1,rel_heights=c(.48,.52));left<-plot_grid(pA,pB,ncol=1,rel_heights=c(.56,.44));right<-plot_grid(pC,pD,ncol=1,rel_heights=c(.55,.45));body<-plot_grid(left,right,ncol=2,rel_widths=c(.54,.46));rib<-ggdraw()+draw_label("Functional and plaque/stone context support a module-level association; causal mediation and external molecular validation remain unresolved.",size=6.8,color=pal["text"])+theme(plot.background=element_rect(fill=pal["vpale"],color=NA));fig<-plot_grid(body,rib,ncol=1,rel_heights=c(.94,.06))
ggsave(paste0(stem,".pdf"),fig,width=180/25.4,height=150/25.4,device="pdf",useDingbats=FALSE,bg="white");ggsave(paste0(stem,".png"),fig,width=180/25.4,height=150/25.4,dpi=600,bg="white");ggsave(paste0(stem,".svg"),fig,width=180/25.4,height=150/25.4,device=svglite::svglite,bg="white")
src<-data.table(panel=c("A","B","C","D","D"),data_file=c("results/tables/go_bp_redundancy_reduced_terms.tsv","results/tables/go_bp_redundancy_reduced_terms.tsv","results/gse73680/tables/gse73680_risk_injury_paired_delta_correlations.tsv","results/plaque/gse73680_risk_injury_coupling.tsv; results/tables/gse73680_risk_injury_leave_one_patient_out.tsv","results/twas/twas_resource_status.tsv; results/smr_coloc/eqtl_resource_status.tsv; results/spatial/spatial_resource_status.tsv"),required_columns=c("gene_set,Description,p.adjust","Description,p.adjust,Count","module_name,injury_module,rho,fdr","analysis,rho,min_rho,median_rho","resource,status or spatial inventory"),values_used=c("observed gene-set/theme links","8 ranked terms","5x4 rho matrix","paired/residual/LOO summaries","availability and blockers"),claim_supported=c("functional context","functional context","injury coupling association","robustness","resource-limited audit only"),notes="no fabricated values");fwrite(src,file.path(od,"figure5_panel_source_files_final.tsv"),sep="\t")
writeLines(c("# Figure 5 legend (final)","","**Figure 5. Functional and disease-context interpretation of MAGMA-prioritized KSD modules.** (A) Evidence network linking gene sets to biological themes using observed redundancy-reduced enrichment. (B) Eight ranked non-redundant GO terms. (C) Compact matrix of paired-delta Spearman coupling between risk modules and injury programs. (D) Residual and leave-one-patient-out robustness with TWAS, SMR/coloc and spatial resource audit. Resource-limited extensions were audited but not used as evidence layers. These analyses do not establish causality, TWAS convergence, SMR/coloc support, spatial validation or P1 single-gene validation."),file.path(od,"figure5_legend_final.md"));writeLines(c("# Figure 5 revision notes (final)","","- Replaced the previous four-statistical-panel layout with network, ranked GO lollipop, one compact coupling matrix, and combined robustness/resource audit.","- Figure 4 paired shifts and random benchmark were not repeated.","- Claim boundary preserved."),file.path(od,"figure5_revision_notes_final.md"));qitems<-c("editable_vector_pass","no_raster_embedding_pass","font_size_min_pass","figure1_4_style_consistency_pass","palette_consistency_pass","panel_balance_pass","label_readability_pass","no_heatmap_overload_pass","no_dotplot_overload_pass","functional_terms_not_overcrowded_pass","injury_coupling_not_causal_pass","twas_not_used_as_result_pass","smr_coloc_not_used_as_result_pass","spatial_not_used_as_result_pass","claim_boundary_pass","journal_like_score","action_required");fwrite(data.table(item=qitems,status=c(rep("TRUE",15),"4.8","minor_manual_review"),notes="final check"),file.path(od,"figure5_visual_qc_final.tsv"),sep="\t");dir.create("docs",showWarnings=FALSE);file.copy(file.path(od,"figure5_legend_final.md"),"docs/figure5_legend_final.md",TRUE);file.copy(file.path(od,"figure5_revision_notes_final.md"),"docs/figure5_revision_notes_final.md",TRUE);file.copy(file.path(od,"figure5_panel_source_files_final.tsv"),"results/tables/figure5_panel_source_files_final.tsv",TRUE);file.copy(file.path(od,"figure5_visual_qc_final.tsv"),"results/tables/figure5_visual_qc_final.tsv",TRUE)
